sandbox.config.cpu-count=1
sandbox.config.memory-limit=268435456
sandbox.config.timeout-limit=2
sandbox.config.time-unit=seconds
sandbox.config.memory-swap=0
sandbox.config.image=compiler:1.0

server.port=7654