server:
  port: ${server.port}

sandbox:
  config:
    cpu-count: ${sandbox.config.cpu-count}
    memory-limit: ${sandbox.config.memory-limit}
    timeout-limit: ${sandbox.config.timeout-limit}
    time-unit: ${sandbox.config.time-unit}
    memory-swap: ${sandbox.config.memory-swap}
    image: ${sandbox.config.image}
